name: condominio_app
description: A Flutter application for managing a condominium with different user profiles.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  http: ^1.1.0
  image_picker: ^1.0.7
  intl: ^0.20.2
  url_launcher: ^6.2.5
  table_calendar: ^3.1.2
  supabase_flutter: ^2.0.0
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  pdf: ^3.10.8
  path_provider: ^2.1.1
  share_plus: ^10.1.4
  app_links: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.5

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - .env

  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/CustomFont.ttf
        - asset: assets/fonts/CustomFont-Bold.ttf
          weight: 700